# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_chunk_full_cpp <- function(X_fixed, w_chunk, z_chunk, lam_diag_chunk, q_total, blocks, X_terms_list, cells_by_grp_list, cell_grp_list, n_threads, stage3_mode = 0L, interior_precision = 0L) {
    .Call(`_PACE_solve_chunk_full_cpp`, X_fixed, w_chunk, z_chunk, lam_diag_chunk, q_total, blocks, X_terms_list, cells_by_grp_list, cell_grp_list, n_threads, stage3_mode, interior_precision)
}

solve_chunk_mb_cpp <- function(X_fixed, w_chunk, z_chunk, lam_diag_chunk, q_total, blocks, ZtWZ_within, XtWZ_within, ZtWz_within, cross_blocks, n_threads) {
    .Call(`_PACE_solve_chunk_mb_cpp`, X_fixed, w_chunk, z_chunk, lam_diag_chunk, q_total, blocks, ZtWZ_within, XtWZ_within, ZtWz_within, cross_blocks, n_threads)
}

